## Numpy Attribute

In [1]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,6), dtype='int64')


In [9]:
print(f'The dimension of array x1 =\t{x1.ndim}')
print(f'The dimension of array x1 =\t{x2.ndim}')
print(f'The dimension of array x1 =\t{x3.ndim}')

The dimension of array x1 =	1
The dimension of array x1 =	2
The dimension of array x1 =	3


In [13]:
print(f'The shape of array x3 =\t{x3.shape}')
print(f'The size of array x3 =\t{x3.size}')

The shape of array x3 =	(3, 4, 6)
The size of array x3 =	72


In [19]:
print(f'The data type of array x1 =\t{x1.dtype}')
print(f'The datatype of array x3 =\t{x3.dtype}')

The data type of array x1 =	int32
The datatype of array x3 =	int64


## Accessing Element

In [21]:
print(x1[0])
print(x2[0])
print(x3[0])

print(x2[0][1])
print(x3[0][1][1])

5
[3 5 2 4]
[[8 1 5 9 8 9]
 [4 3 0 3 5 0]
 [2 3 8 1 3 3]
 [3 7 0 1 9 9]]
5
3


## Array Slicing


In [10]:
x4 = np.arange(10)
print(x4)
print(x4[2 : 5])
print(x4[2 : 8 : 2])
print(x4[: : 2])

# reverse the array
print(x4[::-1])
print(x4[5 :: -2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[2 4 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [ ]:
print(x2)
print("\n")
print(x2[1:]) # rows start with 1st row
print("\n")
print(x2[::2]) # rows with step size 2
print("\n")
print(x2[1:,2::1]) # 1st row and colom start with 2 with step size 1

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


[[7 6 8 8]
 [1 6 7 7]]


[[3 5 2 4]
 [1 6 7 7]]


[[8 8]
 [7 7]]


#### note : 
 One important—and extremely useful—thing to know about array slices is that they
 return views rather than copies of the array data. This is one area in which NumPy
 array slicing differs from Python list slicing: in lists, slices will be copies.

In [46]:
print(x2)
x2_sub_arr = x2[2 : ]
print("before changing the sub array \n")
print(x2_sub_arr)
x2_sub_arr[0][0] = 500
print("After changing the Sub array ")
print(x2_sub_arr)

# we notice oringinal array is also changed.


[[   3    5    2    4]
 [   7    6    8    8]
 [ 500 1000 1000 1000]]
before changing the sub array 

[[ 500 1000 1000 1000]]
After changing the Sub array 
[[ 500 1000 1000 1000]]


This can be resolved using copy method.

In [50]:
print(x2)
x2_sub_arr2 = x2[2:].copy()
print("Before changing :\n")
print(x2_sub_arr2)
x2_sub_arr2[0] = 123
print("After changing \n")
print(x2_sub_arr2)
# note : The original array is not changed.

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Before changing :

[[1 6 7 7]]
After changing 

[[123 123 123 123]]


### Array Reshaping

In [7]:
x1 = np.arange(12).reshape(2,6)
print(x1)
# reshaping the x1 with (3,4)
x2 = x1.reshape(3,4)
# reshape gives the copy
print(x1)
print(x2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
